var Catalog={
  products:[],categories:[],filters:{},
  activeFilters:{categories:[],manufacturers:[],weights:[],availability:[]},
  init:function(data){this.products=data.products||[];this.categories=data.categories||[];this.filters=data.filters||{};this.renderFilters();this.applyUrlFilters();this.renderProducts();this.bindFilterEvents()},
  applyUrlFilters:function(){var cat=Utils.getUrlParam('category');if(cat&&cat!=='all'){this.activeFilters.categories=[cat];var cb=document.querySelector('#filter-categories input[value="'+cat+'"]');if(cb)cb.checked=true}},
  renderFilters:function(){var build=function(cid,items,fk){var el=document.getElementById(cid);if(!el||!items)return;el.innerHTML=items.map(function(it){return'<label class="filter-option"><input type="checkbox" value="'+it.value+'" data-filter="'+fk+'"> '+Utils.escapeHtml(it.label)+'</label>'}).join('')};
    build('filter-categories',this.categories.map(function(c){return{value:c.id,label:c.name}}),'categories');
    build('filter-manufacturers',this.filters.manufacturer,'manufacturers');build('filter-weights',this.filters.weight,'weights');build('filter-availability',this.filters.availability,'availability')},
  bindFilterEvents:function(){var self=this;document.querySelectorAll('[data-filter]').forEach(function(cb){cb.addEventListener('change',function(){var k=this.getAttribute('data-filter'),v=this.value;if(this.checked){if(self.activeFilters[k].indexOf(v)===-1)self.activeFilters[k].push(v)}else{self.activeFilters[k]=self.activeFilters[k].filter(function(x){return x!==v})}self.renderProducts()})});
    var reset=document.getElementById('filter-reset');if(reset)reset.addEventListener('click',function(){self.activeFilters={categories:[],manufacturers:[],weights:[],availability:[]};document.querySelectorAll('[data-filter]').forEach(function(cb){cb.checked=false});self.renderProducts()});
    var toggle=document.getElementById('filter-toggle-btn'),panel=document.getElementById('filters-panel');if(toggle&&panel)toggle.addEventListener('click',function(){panel.classList.toggle('active')})},
  filtered:function(){var af=this.activeFilters;return this.products.filter(function(p){if(af.categories.length&&af.categories.indexOf(p.category)===-1)return false;if(af.manufacturers.length&&af.manufacturers.indexOf(p.manufacturer)===-1)return false;if(af.weights.length&&af.weights.indexOf(p.weight)===-1)return false;if(af.availability.length){var t=p.availability.type==='in-stock'?'in-stock':'on-order';if(af.availability.indexOf(t)===-1)return false}return true})},
  renderProducts:function(){var grid=document.getElementById('catalog-products-grid'),none=document.getElementById('no-products'),count=document.getElementById('products-count');if(!grid)return;var list=this.filtered();if(count)count.textContent='Найдено товаров: '+list.length;if(!list.length){grid.innerHTML='';if(none)none.classList.remove('hidden');return}if(none)none.classList.add('hidden');grid.innerHTML=list.map(this.renderProductCard).join('');this.bindCards()},
  renderProductCard:function(p){var price=p.price.type==='value'?'<span class="product-card-price">'+Utils.formatPrice(p.price.value)+'\u00a0'+p.price.currency+'/'+p.price.unit+'</span>':'<span class="product-card-price ask-manager">Уточняйте у менеджера</span>';
    var avCls=p.availability.type==='in-stock'?'availability-in-stock':'availability-ask';
    var dots='';if(p.photos.gallery&&p.photos.gallery.length>1){dots='<div class="product-card-gallery">'+p.photos.gallery.map(function(_,i){return'<span class="gallery-dot'+(i===0?' active':'')+'" data-index="'+i+'"></span>'}).join('')+'</div>'}
    var gallery=p.photos.gallery?p.photos.gallery.join(','):p.photos.main;
    return'<article class="product-card" data-product-id="'+p.id+'" data-gallery="'+gallery+'"><div class="product-card-image"><img src="'+p.photos.main+'" alt="'+Utils.escapeHtml(p.name)+'" loading="lazy" width="300" height="225">'+dots+'</div><div class="product-card-body"><h3 class="product-card-title">'+Utils.escapeHtml(p.name)+'</h3><p class="product-card-desc">'+Utils.escapeHtml(p.shortDescription)+'</p><div class="product-card-meta">'+price+'<span class="product-card-availability '+avCls+'">'+Utils.escapeHtml(p.availability.text)+'</span></div></div></article>'},
  bindCards:function(){var self=this;document.querySelectorAll('.product-card').forEach(function(card){
    card.addEventListener('click',function(){var id=this.getAttribute('data-product-id');var modal=document.getElementById('product-modal');if(modal)self.openModal(id);else window.location.href='product.html?id='+id});
    var photos=(card.getAttribute('data-gallery')||'').split(',');if(photos.length>1){var img=card.querySelector('.product-card-image img'),dots=card.querySelectorAll('.gallery-dot'),idx=0,iv=null;
    card.addEventListener('mouseenter',function(){iv=setInterval(function(){idx=(idx+1)%photos.length;if(img)img.src=photos[idx];dots.forEach(function(d,i){d.classList.toggle('active',i===idx)})},1200)});
    card.addEventListener('mouseleave',function(){clearInterval(iv);idx=0;if(img)img.src=photos[0];dots.forEach(function(d,i){d.classList.toggle('active',i===0)})})}})},
  openModal:function(id){var p=ConfigLoader.getProductById(id),modal=document.getElementById('product-modal'),det=document.getElementById('product-detail');if(!p||!modal||!det){window.location.href='product.html?id='+id;return}det.innerHTML=this.renderProductDetail(p);modal.classList.add('active');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';this.bindDetail();
    var closeBtn=document.getElementById('product-modal-close');function cls(){modal.classList.remove('active');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}if(closeBtn)closeBtn.onclick=cls;modal.onclick=function(e){if(e.target===modal)cls()}},
  renderProductDetail:function(p){var price=p.price.type==='value'?'<div class="product-price-block"><span class="product-price-value">'+Utils.formatPrice(p.price.value)+'\u00a0'+p.price.currency+'</span><span class="product-price-unit">/ '+p.price.unit+'</span></div>'+(p.price.note?'<p class="product-price-note">'+Utils.escapeHtml(p.price.note)+'</p>':''):'<p class="product-price-ask">Цена: уточняйте у менеджера</p>';
    var avCls=p.availability.type==='in-stock'?'availability-in-stock':'availability-ask';
    var chars='';if(p.characteristics){chars='<div class="product-chars"><h3>Характеристики</h3><table class="chars-table">'+Object.keys(p.characteristics).map(function(k){return'<tr><td>'+Utils.escapeHtml(k)+'</td><td>'+Utils.escapeHtml(p.characteristics[k])+'</td></tr>'}).join('')+'</table></div>'}
    var thumbs='';if(p.photos.gallery&&p.photos.gallery.length>1){thumbs='<div class="product-thumbs">'+p.photos.gallery.map(function(ph,i){return'<div class="product-thumb'+(i===0?' active':'')+'" data-photo="'+ph+'"><img src="'+ph+'" alt="фото '+(i+1)+'" width="80" height="60" loading="lazy"></div>'}).join('')+'</div>'}
    return'<div class="product-layout"><div class="product-gallery"><div class="product-main-image"><img src="'+p.photos.main+'" alt="'+Utils.escapeHtml(p.name)+'" id="product-main-photo" width="400" height="300"></div>'+thumbs+'</div><div class="product-info"><h2 class="product-title">'+Utils.escapeHtml(p.name)+'</h2><p class="product-short-desc">'+Utils.escapeHtml(p.shortDescription)+'</p>'+price+'<span class="product-availability-badge '+avCls+'">'+Utils.escapeHtml(p.availability.text)+'</span><div class="product-actions"><a href="contacts.html" class="btn btn-primary">Связаться с менеджером</a><a href="product.html?id='+p.id+'" class="btn btn-outline">Подробнее</a></div>'+chars+'</div></div><div class="product-full-desc"><h3>Описание</h3><p>'+Utils.escapeHtml(p.fullDescription)+'</p></div>'},
  bindDetail:function(){var mp=document.getElementById('product-main-photo');document.querySelectorAll('.product-thumb').forEach(function(th){th.addEventListener('click',function(e){e.stopPropagation();if(mp)mp.src=this.getAttribute('data-photo');document.querySelectorAll('.product-thumb').forEach(function(t){t.classList.remove('active')});this.classList.add('active')})})}
};
